### ISSUE TITLE
[feature add]建议在ReadME中添加每个重要接口或方法使用说明,这样可直接在Github上阅览api，增加使用率

### ISSUE THREAD

**Issue by markflyfly** [pugwoo/woo-utils#1]
example:
RedisHelper
// 设置字符串
boolean setString(String key, int expireSecond, String value);

**Comment by pugwoo** [comment]
可以参考test目录下的使用demo。由于很多方法都很简单，尽量以static工具类方式提供，同时utils发布速度较快，故不计划在README.md列上每个api，请直接看源码吧，都很清晰直接。
