### ISSUE TITLE
redisHelper无法设置key为永不过期？

### ISSUE THREAD

**Issue by markflyfly** [pugwoo/woo-utils#2]
1.实际需求存在有设置为永不过期的数据需求
2.不设为永久有可能为会在未来埋坑，找不到key值

**Comment by pugwoo** [comment]
从接口设计的角度考虑，要求给超时时间是为了避免忘记考虑缓存的有效期的情况。

从缓存的使用角度考虑，所有缓存的数据都应该是有超时时间的，这是缓存的合理特点。所以，当你有一个永久的缓存，说明在这方面考虑是不太周全的，持久的数据建议存到关系型DB中，缓存不应该变成长期强依赖的条件。

如果一个数据需要缓存很久，可以将超时时间设置为10年或50年。
