### ISSUE TITLE
【建议】有时候使用redisHelper一段时间后每隔一段时间就会出现：java.util.NoSuchElementException: Timeout waiting for idle object

### ISSUE THREAD

**Issue by markflyfly** [pugwoo/woo-utils#3]
建议修改从连接池获取连接的方法，获取连接失败时，调用returnBrokenResource方法。
try {
jedis = pool.getResource();
} catch (RuntimeException e) { 
         if(jedis != null ) {
                 pool.returnBrokenResource(jedis);//获取连接失败时，应该返回给pool,否则每次发生异常将导致一个jedis对象没有被回收。
}
}

**Comment by pugwoo** [comment]
已处理此bug，发布为0.4.5版本，2个小时后中央仓库可以看到，看看还有没有问题

**Comment by markflyfly** [comment]
@pugwoo 感谢

**Comment by markflyfly** [comment]
@pugwoo 包括hessian那块的redis获取连接时也存在这样的问题，那个1秒钟检查服务url是否可用也是不断的获取连接释放连接，在某些情况下也会出现这样的问题

**Comment by pugwoo** [comment]
@markflyfly hessoa已经修复并发布为0.5.3版本，2个小时后中央仓库可见。hessoa很久没有开发了，如果有项目实际在用，可以提些想法并欢迎PR

**Comment by markflyfly** [comment]
自己个人还没有实际项目在用,目前公司里基本都是dubbo，不过hessoa可以作为中小型项目的一个轻量级soa解决方案。

**Comment by pugwoo** [comment]
@markflyfly 大概了解过spring cloud，它还是相对理想化。在实际项目中，还是dubbo更贴合。hessoa的功能和dubbo基本是对等的，但是没有在大规模系统中使用，不过hessoa只有1500行代码左右，是对hessian的简单封装，要改动和定制就相对灵活很多
